Repository Mash-Up-MapC/MapC-backend, pull requests merged in 2018-08, with the labels that each got.

#36 개발 진행을 위한 code base의 사전 작업하기 1차
  build.gradle
  src/main/java/kr/co/mashup/mapc/MapcApplication.java
  src/main/java/kr/co/mashup/mapc/common/config/SwaggerConfiguration.java
  src/main/java/kr/co/mashup/mapc/controller/ColorController.java
Labels: needs review

#43 민감 정보인 Database 연결 정보를 환경변수에서 가져오도록 수정
  build.gradle
  src/main/resources/application.properties
Labels: needs review

#44 [#34][BUG] 에러 - No identifier specified for entity
  src/main/java/kr/co/mashup/mapc/entity/Course.java
  src/main/java/kr/co/mashup/mapc/entity/InformationType.java
Labels: bug

#45 Feature/is25 mock api
  src/main/java/kr/co/mashup/mapc/config/SwaggerConfiguration.java
  src/main/java/kr/co/mashup/mapc/controller/CourseController.java
  src/main/java/kr/co/mashup/mapc/dto/CourseDto.java
  src/main/java/kr/co/mashup/mapc/dto/CourseRoute.java
  src/main/java/kr/co/mashup/mapc/dto/DataResponse.java
  src/main/java/kr/co/mashup/mapc/dto/DetailCourse.java
  src/main/java/kr/co/mashup/mapc/dto/Location.java
  src/main/java/kr/co/mashup/mapc/dto/ReservationCourse.java
  src/main/java/kr/co/mashup/mapc/dto/Station.java
  src/main/java/kr/co/mashup/mapc/dto/TouristAttractions.java
  src/main/java/kr/co/mashup/mapc/entity/BaseTimeEntity.java
  src/main/java/kr/co/mashup/mapc/entity/Booking.java
  src/main/java/kr/co/mashup/mapc/entity/Company.java
  src/main/java/kr/co/mashup/mapc/entity/Course.java
  src/main/java/kr/co/mashup/mapc/entity/CourseImage.java
  src/main/java/kr/co/mashup/mapc/entity/Information.java
  src/main/java/kr/co/mashup/mapc/entity/InformationType.java
  src/main/java/kr/co/mashup/mapc/entity/Price.java
  src/main/java/kr/co/mashup/mapc/entity/Station.java
  src/main/java/kr/co/mashup/mapc/entity/StationImage.java
  src/main/java/kr/co/mashup/mapc/entity/Tourist.java
  src/main/java/kr/co/mashup/mapc/entity/TypeDefine.java
  src/main/java/kr/co/mashup/mapc/repository/BookingRepository.java
  src/main/java/kr/co/mashup/mapc/repository/TouristRepository.java
  src/main/java/kr/co/mashup/mapc/service/BookingService.java
  src/main/java/kr/co/mashup/mapc/service/CourseService.java
  src/main/resources/application.properties
Labels: under review
